### ISSUE TITLE
External storage problem after MM update

### ISSUE THREAD

**Issue by aperomsik** [OpenSilk/Orpheus#18]
My phone got Android 6 yesterday. Now albums which were already in my library seem to still work OK, but the "folders" tab is completely blank.

On the "other library" area, the folders tab shows internal and external areas, but when I browse inside the strangely named folder that is supposed to be my sdcard, I get an error message, "there was an error loading the items."

**Comment by drewis** [comment]
I only have one M device and it doesnt have removable storage. Can you post a logcat. When you click on the sdcard in Other Libraries it will dump a somewhat lengthy paragraph with the error

**Comment by aperomsik** [comment]
```
01-07 08:06:05.603 19490 19490 W ActionBarDrawerToggle: DrawerToggle may not show up because NavigationIcon is not visible. You may need to call actionbar.setDisplayHomeAsUpEnabled(true);
01-07 08:06:05.604 19490 19490 D MortarFragment: Created new fragment scope org.opensilk.music.ui3.library.FoldersScreen-content://org.opensilk.music.provider.foldersLibrary/-917438463/folders
01-07 08:06:05.606   281   845 D audio_hw_primary: out_set_parameters: enter: usecase(0: deep-buffer-playback) kvpairs: routing=2
01-07 08:06:05.606   281   845 V msm8916_platform: platform_get_output_snd_device: enter: output devices(0x2)
01-07 08:06:05.606   281   845 V msm8916_platform: platform_get_output_snd_device: exit: snd_device(speaker)
01-07 08:06:05.606   281   845 D audio_hw_extn: audio_extn_set_anc_parameters: anc_enabled:0
01-07 08:06:05.606   281   845 E soundtrigger: audio_extn_sound_trigger_set_parameters: str_params NULL
01-07 08:06:05.607  5134  5745 D MotoNetwCtrlr: onReceive: intent=Intent { act=android.net.wifi.RSSI_CHANGED flg=0x4000010 (has extras) }
01-07 08:06:05.608  5134  5745 I MotoNetwCtrlr.MotoWifiSignalCtrlr: handleBroadcast: Entered: Intent=Intent { act=android.net.wifi.RSSI_CHANGED flg=0x4000010 (has extras) } Action=android.net.wifi.RSSI_CHANGED
01-07 08:06:05.618 19490 19490 V FooterScreenPresenter: onEnterScope()
01-07 08:06:05.620 19490 19490 V FooterScreenPresenter: onLoad()
01-07 08:06:05.628 19506 19516 W FoldersLibraryProvider: Unmatched uri content://org.opensilk.music.provider.foldersLibrary/-917438463/folders [Binder_1]
01-07 08:06:05.635   281   845 D AudioFlinger: mixer(0xb431e008) throttle end: throttle time(40)
01-07 08:06:05.662 19490 19503 E TypedBundleableLoader: BundleableLoader(
01-07 08:06:05.662 19490 19503 E TypedBundleableLoader: uri=content://org.opensilk.music.provider.foldersLibrary/-917438463/folders
01-07 08:06:05.662 19490 19503 E TypedBundleableLoader: sortOrder=name
01-07 08:06:05.662 19490 19503 E TypedBundleableLoader: ) ex=
01-07 08:06:05.662 19490 19503 E TypedBundleableLoader: org.opensilk.music.library.internal.LibraryException: java.lang.IllegalArgumentException: Invalid uri content://org.opensilk.music.provider.foldersLibrary/-917438463/folders
01-07 08:06:05.662 19490 19503 E TypedBundleableLoader:     at org.opensilk.music.library.internal.LibraryException$1.createFromParcel(LibraryException.java:106)
01-07 08:06:05.662 19490 19503 E TypedBundleableLoader:     at org.opensilk.music.library.internal.LibraryException$1.createFromParcel(LibraryException.java:104)
01-07 08:06:05.662 19490 19503 E TypedBundleableLoader:     at org.opensilk.music.library.internal.IBundleableObserver$Stub.onTransact(IBundleableObserver.java:63)
01-07 08:06:05.662 19490 19503 E TypedBundleableLoader:     at android.os.Binder.execTransact(Binder.java:453)
01-07 08:06:05.662 19490 19503 E TypedBundleableLoader: Caused by: java.lang.IllegalArgumentException: Invalid uri content://org.opensilk.music.provider.foldersLibrary/-917438463/folders
01-07 08:06:05.662 19490 19503 E TypedBundleableLoader:     at org.opensilk.music.library.mediastore.provider.FoldersLibraryProvider$4.call(FoldersLibraryProvider.java:318)
01-07 08:06:05.662 19490 19503 E TypedBundleableLoader:     at org.opensilk.music.library.mediastore.provider.FoldersLibraryProvider$4.call(FoldersLibraryProvider.java:304)
01-07 08:06:05.662 19490 19503 E TypedBundleableLoader:     at rx.Observable$2.call(Observable.java:162)
01-07 08:06:05.662 19490 19503 E TypedBundleableLoader:     at rx.Observable$2.call(Observable.java:154)
01-07 08:06:05.662 19490 19503 E TypedBundleableLoader:     at rx.Observable.subscribe(Observable.java:8264)
01-07 08:06:05.662 19490 19503 E TypedBundleableLoader:     at rx.Observable.subscribe(Observable.java:8231)
01-07 08:06:05.662 19490 19503 E TypedBundleableLoader:     at org.opensilk.music.library.mediastore.provider.FoldersLibraryProvider.listObjsInternal(FoldersLibraryProvider.java:296)
01-07 08:06:05.662 19490 19503 E TypedBundleableLoader:     at org.opensilk.music.library.provider.LibraryProvider.call(LibraryProvider.java:132)
01-07 08:06:05.662 19490 19503 E TypedBundleableLoader:     at android.content.ContentProvider$Transport.call(ContentProvider.java:398)
01-07 08:06:05.662 19490 19503 E TypedBundleableLoader:     at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:283)
01-07 08:06:05.662 19490 19503 E TypedBundleableLoader:     ... 1 more
01-07 08:06:05.662 19490 19503 E TypedBundleableLoader:  [Binder_2]
```

**Comment by drewis** [comment]
3.2 will roll out tonight. it fixes that error. but im afraid it may be a symptom of a larger issue. its possible the id on the sdcard changed during the update, orphaning all your indexed music. orpheus cant handle orphans yet so you may need to clear the app data and redo the index. i probably shouldnt have used the storage ids at all but they were supposed to be stable, ill have to think through a way to handle migrating away from them without screwing everything up.
